name: responsibleai-text
channels:
  - conda-forge
  - defaults
  - huggingface
  - anaconda
  - pytorch
dependencies:
  - python=3.8
  - pip
  - pytorch
  - torchvision
  - captum
  - cpuonly
  - pip:
    - numpy==1.22.0
    - responsibleai~=0.26.0
    - raiwidgets~=0.26.0
    - pyarrow
    - azure-core==1.25.1
    - mlflow
    - markupsafe<2.1.0
    - itsdangerous==2.0.1
<<<<<<< HEAD
    - responsibleai-text==0.0.1
=======
    - responsibleai-text==0.1.2
>>>>>>> dd72eed5437b545560c6458999e9e9ba590778de
    - click<8.0.0
    - mltable==1.0.0
    - transformers>=4.17.0
    - ml-wrappers~=0.4.2
    - nlp-feature-extractors==0.1.0
    - datasets
