name: llm-dbcopilot-embeddings
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - pip=21.3.1
  - pip:
      - azureml-rag[cognitive_search,data_generation]>=0.1.16
      - langchain==0.0.220
      - azureml-contrib-services
      - azure-identity==1.12.0
      - azureml-core==1.52.0
      - azure-ai-ml~=1.4.0
      - cryptography>=41.0.3
