$schema: https://azuremlschemas.azureedge.net/latest/pipelineComponent.schema.json
type: pipeline

name: generation_safety_quality_signal_monitor
display_name: Generation Safety & Quality - Signal Monitor
description: Computes the content generation safety metrics over LLM outputs.
version: 0.5.6
is_deterministic: true
inputs:
  monitor_name:
    type: string
  signal_name:
    type: string
  production_data:
    type: mltable
  metric_names:
    type: string
    description: a comma-separated list of metric names to compute
    optional: false
  model_deployment_name:
    type: string
    optional: false
    description: model name, e.g., name of the deployment for Azure OpenAI
  sample_rate:
    type: number
    optional: true
    description: sample rate for the input dataset, should be greater than 0 and at most 1
  prompt_column_name:
    type: string
    optional: true
    default: "prompt"
  completion_column_name:
    type: string
    optional: true
    default: "completion"
  ground_truth_column_name:
    type: string
    optional: true
    default: "ground_truth"
  context_column_name:
    type: string
    optional: true
    default: "context"
  groundedness_rating_threshold:
    type: integer
    optional: true
    default: 4
  similarity_rating_threshold:
    type: integer
    optional: true
    default: 4
  relevance_rating_threshold:
    type: integer
    optional: true
    default: 4
  fluency_rating_threshold:
    type: integer
    optional: true
    default: 4
  coherence_rating_threshold:
    type: integer
    optional: true
    default: 4
  groundedness_passrate_threshold:
    type: number
    optional: true
    default: 0.7
  similarity_passrate_threshold:
    type: number
    optional: true
    default: 0.7
  relevance_passrate_threshold:
    type: number
    optional: true
    default: 0.7
  fluency_passrate_threshold:
    type: number
    optional: true
    default: 0.7
  coherence_passrate_threshold:
    type: number
    optional: true
    default: 0.7
  workspace_connection_arm_id:
    type: string
    optional: false
  monitor_current_time:
    type: string
  notification_emails:
    type: string
    default: ""
    optional: true
outputs:
  signal_output:
    type: uri_folder
    mode: direct
jobs:
  compute_histogram:
    type: spark
    component: azureml://registries/yunzhan-westus2/components/gsq_annotation_compute_histogram/versions/0.5.6
    inputs:
      production_dataset:
        type: mltable
        path: ${{parent.inputs.production_data}}
      metric_names: ${{parent.inputs.metric_names}}
      model_deployment_name: ${{parent.inputs.model_deployment_name}}
      sample_rate: ${{parent.inputs.sample_rate}}
      workspace_connection_arm_id: ${{parent.inputs.workspace_connection_arm_id}}
      groundedness_rating_threshold: ${{parent.inputs.groundedness_rating_threshold}}
      similarity_rating_threshold: ${{parent.inputs.similarity_rating_threshold}}
      relevance_rating_threshold: ${{parent.inputs.relevance_rating_threshold}}
      fluency_rating_threshold: ${{parent.inputs.fluency_rating_threshold}}
      coherence_rating_threshold: ${{parent.inputs.coherence_rating_threshold}}
      ground_truth_column_name: ${{parent.inputs.ground_truth_column_name}}
      prompt_column_name: ${{parent.inputs.prompt_column_name}}
      completion_column_name: ${{parent.inputs.completion_column_name}}
      context_column_name: ${{parent.inputs.context_column_name}}
    outputs:
      histogram:
        type: mltable
      samples_index:
        type: mltable
      groundedness_violations:
        type: mltable
      coherence_violations:
        type: mltable
      relevance_violations:
        type: mltable
      fluency_violations:
        type: mltable
      similarity_violations:
        type: mltable
      signal_output:
        type: uri_folder
        path: ${{parent.outputs.signal_output}}
        mode: direct
    resources:
      instance_type: standard_e4s_v3
      runtime_version: "3.3"
    identity:
      type: aml_token
