image:
  name: azureml/curated/responsibleai-vision-ubuntu22.10-py38-cpu
  os: linux
  context:
    dir: context
    dockerfile: Dockerfile
    template_files:
    - Dockerfile
    - conda_dependencies.yaml
  publish:
    location: mcr
    visibility: public
