name: sklearn-1.1
channels:
- anaconda
- conda-forge
dependencies:
- python=3.8
- pip=21.3.1
- pandas~=1.3.0
- scipy~=1.10.0
- numpy~=1.22.0
- pip:
  - scikit-learn-intelex==2023.2.1
  - wheel~=0.38.1
  - azureml-core==1.52.0
  - azureml-defaults==1.52.0
  - azureml-mlflow==1.52.0
  - azureml-telemetry==1.52.0
  - azureml-automl-common-tools==1.52.0
  - scikit-learn~=1.1.0
  - joblib~=1.2.0
  - cryptography>=41.0.2
