name: llm-auto-prompt
channels:
- conda-forge
dependencies:
- python=3.8
- pip=21.2.4
- pip:
  - azureml-rag[cognitive_search,data_generation]>=0.1.23
  - matplotlib>=3.3,<3.4
  - psutil>=5.8,<5.9
  - tqdm>=4.59,<4.60
  - pandas>=1.1,<1.2
  - scipy>=1.10.0
  - numpy>=1.22
  - ipykernel~=6.0
  - azureml-core==1.53.0
  - azureml-telemetry==1.53.0
  - azureml-train-core==1.53.0
  - azureml-mlflow==1.53.0
  - scikit-learn==0.24.1
  - mltable
  - transformers==4.30.0
  - torch~=1.11
  - openai~=0.27.4
  - azure-ai-ml~=1.8.0
  - bert_score
  - seaborn
  - sentence-transformers
  - tenacity==8.2.2
  - cryptography>=41.0.3
  - tornado>=6.3.3