name: automl-gpu
channels:
- anaconda
- conda-forge
dependencies:
- python=3.8
- pip=22.1.2
- pytorch=1.9.0
- numpy~=1.22.3
- scikit-learn=0.22.1
- pandas~=1.1.5
- py-xgboost=1.3.3
- holidays=0.10.3
- cudatoolkit=11.1
- pyopenssl=23.2.0
- psutil>=5.2.2,<6.0.0
- GitPython=3.1.30
- scipy~=1.7.0
- tqdm
- setuptools=65.5.1
- wheel=0.38.1
- openssl=1.1.1s
- pip:
  - inference-schema
  - cryptography==41.0.0
  - azureml-core==1.53.0
  - azureml-mlflow==1.53.0
  - azureml-defaults==1.53.0
  - azureml-telemetry==1.53.0
  - azureml-interpret==1.53.0
  - azureml-responsibleai==1.53.0
  - azureml-automl-core==1.53.0
  - azureml-automl-runtime==1.53.0
  - azureml-train-automl-client==1.53.0
  - azureml-train-automl-runtime==1.53.0
  - azureml-dataset-runtime==1.53.0
  - azureml-contrib-dataset==1.53.0
  - azureml-train-automl==1.53.0
  - azureml-contrib-automl-dnn-forecasting==1.53.0
  - https://aka.ms/automl-resources/packages/en_core_web_sm-2.1.0.tar.gz
  - spacy==2.1.8
  - fbprophet==0.7.1
  - pystan==2.19.1.1
  - py-cpuinfo==5.0.0