name: lightgbm-3.3
channels:
- anaconda
- conda-forge
dependencies:
- python=3.8
- pip=21.3.1
- pandas>=1.1,<1.2
- scipy~=1.5.0
- numpy~=1.22.0
- pip:
  - wheel~=0.38.1
  - azureml-core==1.52.0
  - azureml-defaults==1.52.0
  - azureml-mlflow==1.52.0
  - azureml-telemetry==1.52.0
  - azureml-automl-common-tools==1.52.0
  - scikit-learn~=0.24.1
  - xgboost~=1.4.0
  - lightgbm~=3.3.5
  - distributed~=2021.10.0
  - adlfs~=0.7.0
