name: data-labeling
channels:
- conda-forge
- pytorch
dependencies:
- python=3.9
- pip=21.3.1
- pip:
  - azureml-core==1.52.0
  - azureml-contrib-dataset==1.52.0
  - azureml-dataset-runtime[fuse,pandas]
  - azureml-defaults==1.52.0
  - azure-storage-blob==12.14.1
  - Pillow==9.5.0
  - pycairo==1.20.1
  - pydicom==2.4.1
  - python-rle==0.0.3
  
