name: python-sdk-v2
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.2.4
  - pip:
    - azure-ai-ml==1.9.0
    - azure-identity==1.13.0
    # v1 package for fetching run details
    - azureml-core==1.52.0
    # v1 package for logging and telemetry. Switch to using application-insights and implementing custom logging
    - azureml-telemetry==1.52.0
    - cryptography==41.0.2
    - certifi==2023.7.22
