name: python-sdk-v2
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.2.4
  - pip:
    - azure-ai-ml==1.8.0
    - azure-identity==1.13.0
    - azureml-core==1.52.0
    - azureml-automl-core==1.52.0
    - azureml-telemetry==1.52.0
