name: python-sdk-v2
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.2.4
  - pip:
    - azure-core==1.26.4
    - azure-ai-ml==1.6.0
    - azure-identity==1.13.0
    - azureml-core==1.50.0
