$schema: https://azuremlschemas.azureedge.net/latest/pipelineComponent.schema.json
type: pipeline

name: batch_benchmark_inference_deployment
display_name: Batch Benchmark Inference (Managed Deployment)
description: Components for batch endpoint inference With Managed Deployment
version: 0.0.3

inputs:
  input_dataset:
    type: uri_folder
    description: Input jsonl dataset that contains prompt.  For the performance test, this one will be neglected.
    optional: True
  batch_input_pattern:
    type: string
    description: >- 
      The string for the batch input pattern. The input should be the payload format with substitution
      for the key for the value put in the `###<key>`. For example, one can use the following format for
      a llama text-gen model with a input dataset has `prompt` for the payload
      and `_batch_request_metadata` storing the corresponding ground truth.
      {
        "input_data":
        {
          "input_string": ["###<prompt>"],
          "parameters":
          {
            "temperature": 0.6,
            "max_new_tokens": 100,
            "do_sample": true
          }
        },
        "_batch_request_metadata": ###<_batch_request_metadata>
      }

      For AOAI model, the following pattern can be used,
      {
          "messages":
          [
            {"role": "user", "content": "###<prompt>" } ],
            "temperature": 0.7,
            "top_p": 0.95,
            "frequency_penalty": 0,
            "presence_penalty": 0,
            "max_tokens": 800,
            "stop": null
      }
    optional: False
  label_column_name:
    type: string
    optional: True
    description: The label column name.
  n_samples:
    type: integer
    description: The number of top samples send to endpoint. When performance test is enabled, this will be the number of repeated samples send to the endpoint.
    optional: True
  handle_response_failure:
    type: string
    optional: False
    description: The way that the formatter handles the failed response.
    enum:
      - use_fallback
      - neglect
    default: use_fallback
  fallback_value:
    description: The fallback value that can be used when request payload failed. If not provided, the fallback value will be an empty string.
    type: string
    optional: True
  additional_headers:
    type: string
    optional: True
    description: A stringified json expressing additional headers to be added to each request.
  ensure_ascii:
    type: boolean
    optional: False
    default: False
    description: If ensure_ascii is true, the output is guaranteed to have all incoming non-ASCII characters escaped. If ensure_ascii is false, these characters will be output as-is. More detailed information can be found at https://docs.python.org/3/library/json.html
  endpoint_subscription:
    type: string
    optional: True
    description: The subscription id for the endpoint. If empty, the same subscription as workspace will be used.
  endpoint_resource_group:
    type: string
    optional: True
    description: The resource group for the endpoint. If empty, the same resource group as workspace will be used.
  endpoint_region:
    type: string
    optional: True
    description: The region for the endpoint. If empty, the same region as workspace will be used.
  deployment_sku:
    type: string
    optional: True
    description: The sku for the deployment. Only needed for managed deployment.
  endpoint_name:
    type: string
    optional: True
    description: The name for the endpoint. If empty, a random one will be used.
  model:
    type: string
    optional: True
    description: The model name/asset url.
  model_version:
    type: string
    optional: True
    description: The model version.
  is_finetuned_model:
    type: boolean
    optional: True
    default: False
    description: If the model is a finetuned model.
  finetuned_subscription_id:
    type: string
    optional: True
    description: The subscription id for the finetuned model.
  finetuned_resource_group:
    type: string
    optional: True
    description: The resource group for the finetuned model.
  finetuned_workspace:
    type: string
    optional: True
    description: The workspace name for the finetuned model.
  delete_managed_resources:
    type: boolean
    optional: True
    default: True
    description: If true, the managed resources created during the run will be deleted.
  deployment_name:
    type: string
    optional: True
    description: The deployment name. Only needed for managed OSS deployment.
  connections_name:
    type: string
    optional: True
    description: Connections name for the endpoint.
  max_retry_time_interval:
    type: integer
    optional: True
    description: The maximum time (in seconds) spent retrying a payload. If unspecified, payloads are retried unlimited times.
  initial_worker_count:
    type: integer
    optional: False
    default: 5
    description: The initial number of workers to use for scoring.
  max_worker_count:
    type: integer
    optional: False
    default: 200
    description: Overrides initial_worker_count if necessary
  instance_count:
    type: integer
    default: 1
    description: 'Number of nodes in a compute cluster we will run the train step on.'
  max_concurrency_per_instance:
    type: integer
    default: 1
    description: Number of processes that will be run concurrently on any given node. This number should not be larger than 1/2 of the number of cores in an individual node in the specified cluster.
  debug_mode:
    type: boolean
    optional: False
    default: False
    description: Enable debug mode will print all the debug logs in the score step.
  do_quota_validation:
    type: boolean
    optional: True
    default: True
    description: If doing quota valiation or not for AOAI model.
  use_max_quota:
    type: boolean
    optional: True
    default: True
    description: If using max quota or not for AOAI model.
  mini_batch_size:
    type: string
    optional: True
    default: "100KB"
    description: The mini batch size for parallel run.
  delete_managed_deployment:
    type: boolean
    optional: True
    default: True
    description: If deleting the managed deployment.
  deployment_retries:
    type: integer
    optional: True
    default: 1
    description: The number of retries for deployment.
  deployment_retry_interval_seconds:
    type: integer
    optional: True
    default: 60
    description: The interval seconds for deployment retry.
  wait_finetuned_step:
    type: boolean
    optional: True
    default: False
    description: If waiting the finetuned step to finish.
  finetuned_step_name:
    type: string
    optional: True
    description: The finetuned step name.
  authentication_type:
    type: string
    optional: False
    description: Authentication type for end endpoint.
    default: azureml_workspace_connection
    enum:
      - azureml_workspace_connection
      - managed_identity
outputs:
  predictions:
    type: uri_file
    description: The prediction data.
  performance_metadata:
    type: uri_file
    description: The performance data.
  ground_truth:
    type: uri_file
    description: The ground truth data that has a one-to-one mapping with the prediction data.

jobs:
  # Deployment
  model_deployment:
    type: command
    component: azureml:batch_resource_manager:0.0.1
    inputs:
      endpoint_name: ${{parent.inputs.endpoint_name}}
      deployment_name: ${{parent.inputs.deployment_name}}
      model: ${{parent.inputs.model}}
      model_version: ${{parent.inputs.model_version}}
      model_type: oai
      deployment_sku: ${{parent.inputs.deployment_sku}}
      endpoint_resource_group: ${{parent.inputs.endpoint_resource_group}}
      endpoint_subscription_id: ${{parent.inputs.endpoint_subscription}}
      endpoint_location: ${{parent.inputs.endpoint_region}}
      connections_name: ${{parent.inputs.connections_name}}
      deletion_model: false
      do_quota_validation: ${{parent.inputs.do_quota_validation}}
      use_max_quota: ${{parent.inputs.use_max_quota}}
      is_finetuned_model: ${{parent.inputs.is_finetuned_model}}
      finetuned_subscription_id: ${{parent.inputs.finetuned_subscription_id}}
      finetuned_resource_group: ${{parent.inputs.finetuned_resource_group}}
      finetuned_workspace: ${{parent.inputs.finetuned_workspace}}
      deployment_retries: ${{parent.inputs.deployment_retries}}
      deployment_retry_interval_seconds: ${{parent.inputs.deployment_retry_interval_seconds}}
      wait_finetuned_step: ${{parent.inputs.wait_finetuned_step}}
      finetuned_step_name: ${{parent.inputs.finetuned_step_name}}
  # Preparer
  batch_inference_preparer: 
    type: command
    component: azureml:batch_inference_preparer:0.0.3
    inputs:
      input_dataset: ${{parent.inputs.input_dataset}}
      model_type: oai
      batch_input_pattern: ${{parent.inputs.batch_input_pattern}}
      is_performance_test: false
      n_samples: ${{parent.inputs.n_samples}}
      endpoint_url: "a_url"
      label_column_name: ${{parent.inputs.label_column_name}}
    outputs:
      formatted_data:
        type: mltable
      ground_truth_metadata:
        type: uri_folder
  # Inference
  endpoint_batch_score:
    type: parallel
    component: azureml://registries/azureml-batch-score/components/batch_score_llm/versions/1.8.20231130.2
    inputs:
      append_row_safe_output: true
      api_type: completion
      scoring_url: "a_url"
      debug_mode: ${{parent.inputs.debug_mode}}
      additional_headers: ${{parent.inputs.additional_headers}}
      ensure_ascii: ${{parent.inputs.ensure_ascii}}
      max_retry_time_interval: ${{parent.inputs.max_retry_time_interval}}
      tally_failed_requests: true
      tally_exclusions: none
      segment_large_requests: disabled
      segment_max_token_size: 600
      output_behavior: append_row
      initial_worker_count: ${{parent.inputs.initial_worker_count}}
      max_worker_count: ${{parent.inputs.max_worker_count}}
      data_input_table: ${{parent.jobs.batch_inference_preparer.outputs.formatted_data}}
      configuration_file: ${{parent.jobs.model_deployment.outputs.output_metadata}}
      authentication_type: ${{parent.inputs.authentication_type}}
      async_mode: false
    outputs:
      job_out_path:
        type: uri_file
      mini_batch_results_out_directory:
        type: uri_folder
      metrics_out_directory:
        type: uri_folder
    resources:
      instance_count: ${{parent.inputs.instance_count}}
    max_concurrency_per_instance:  ${{parent.inputs.max_concurrency_per_instance}}
    mini_batch_size: "100KB"
    retry_settings:
      timeout: 6000
      max_retries: 10
  # Reformat
  batch_output_formatter: 
    type: command
    component: azureml:batch_output_formatter:0.0.3
    inputs:
      model_type: oai
      batch_inference_output: ${{parent.jobs.endpoint_batch_score.outputs.mini_batch_results_out_directory}}
      label_column_name: ${{parent.inputs.label_column_name}}
      ground_truth_input: ${{parent.jobs.batch_inference_preparer.outputs.ground_truth_metadata}}
      fallback_value: ${{parent.inputs.fallback_value}}
      handle_response_failure: ${{parent.inputs.handle_response_failure}}
      is_performance_test: false
    outputs:
      predictions:
        type: uri_file
        path: ${{parent.outputs.predictions}}
      performance_metadata:
        type: uri_file
        path: ${{parent.outputs.performance_metadata}}
      ground_truth:
        type: uri_file
        path: ${{parent.outputs.ground_truth}}
    # Delete deployment
  delete_deployment:
    type: command
    component: azureml:batch_resource_manager:0.0.1
    inputs:
      deployment_metadata: ${{parent.jobs.model_deployment.outputs.output_metadata}}
      wait_input: ${{parent.jobs.endpoint_batch_score.outputs.job_out_path}}
      delete_managed_deployment: ${{parent.inputs.delete_managed_deployment}}
