image:
  name: azureml/curated/text-generation-inference
  os: linux
  context:
    dir: context
    dockerfile: Dockerfile
    template_files:
    - Dockerfile
    - requirements.txt
    - score.py
  publish:
    location: mcr
    visibility: public