name: sklearn-1.0
channels:
- anaconda
- conda-forge
dependencies:
- python=3.8
- pip=21.3.1
- pandas~=1.3.0
- scipy~=1.7.0
- numpy~=1.22.0
- pip:
  - wheel~=0.38.1
  - azureml-core==1.51.0
  - azureml-defaults==1.51.0
  - azureml-mlflow==1.51.0
  - azureml-telemetry==1.51.0
  - azureml-automl-common-tools==1.51.0
  - scikit-learn~=1.0.0
  - joblib~=1.2.0

