name: data-labeling-sam
channels:
- conda-forge
- pytorch
dependencies:
- python=3.9
- pip=23.3
- pip:
  - azureml-core=={{latest-pypi-version}}
  - azureml-contrib-dataset=={{latest-pypi-version}}
  - azureml-dataset-runtime[fuse,pandas]>=1.54.0
  - azureml-defaults=={{latest-pypi-version}}
  - azure-ml-component==0.9.18.post2
  - azureml-mlflow=={{latest-pypi-version}}
  - azureml-contrib-services=={{latest-pypi-version}}
  - azureml-automl-common-tools=={{latest-pypi-version}}
  - azureml-inference-server-http~=0.8.0
  - inference-schema~=1.5.0
  - opencv-python-headless
  - pyarrow>=14.0.1
  - pycocotools
  - Pillow
  - regex
  - torch
  - torch-tb-profiler~=0.4.0
  - torchvision
  - git+https://github.com/facebookresearch/segment-anything.git
