name: bert-base-uncased workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "31 10/12 * * *"
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/import-bert-base-uncased.yaml

jobs:
  import-model-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Azure/azureml-examples PUBLIC repository
        uses: actions/checkout@v2
        with:
          owner: 'Azure'
          repository: 'Azure/azureml-examples'
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: pip install notebook reqs
        run: pip install -r sdk/python/dev-requirements.txt
      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZUREML_CREDENTIALS}}