name: model-monitoring-ci

on:
  push:
    branches:
      - main
    paths: 
      - model_monitoring/**
  workflow_dispatch:

concurrency: ${{ github.workflow }}

env:
  momoComponentsRootPath: main/model_monitoring/components
  testsRootPath: main/model_monitoring/components/tests

permissions:
  # Required to clone repo
  contents: read
  # Required for OIDC login to Azure
  id-token: write

defaults:
  run:
    shell: cmd

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: windows-latest

    steps:
      - name: Clone branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ${{ env.main_dir }}
      
      
      - name: Use Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
    
      - name: Install dependencies
        run: python -m pip install -r $(testsRootPath)/requirements.txt
